on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout na branch develop
        uses: actions/checkout@v4
        with:
          ref: develop
      - name: Versão atual da aplicação
        run: |
          VERSION=$(grep -oP '(?<=<version>)[^<]+' pom.xml | sed -n '2p')
          echo "Versão: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
      - name: Atualizando versão no pom.xml
        run: |
          grep -E '<version>[0-9]+\.[0-9]+\.[0-9]+</version>' pom.xml
          git config user.email dherkyan@gmail.com
          git config user.name 'CI Automation'
          sed -Ei 's/(<version>)([0-9]+\.[0-9]+\.)([0-9]+)(<\/version>)/echo "\1\2$((\3+1))\4"/ge' pom.xml
          git add pom.xml
          git log --oneline -10
          git commit -m"v-${{env.version}}"
          git push origin develop
          grep -E '<version>[0-9]+\.[0-9]+\.[0-9]+</version>' pom.xml
