on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4
      - name: Atualizando versão no pom.xml
        run: |
          grep -E '<version>[0-9]+\.[0-9]+\.[0-9]+</version>' pom.xml
          git config user.email dherkyan@gmail.com
          git config user.name 'CI Automation'
          sed -E 's/(<version>)([0-9]+\.[0-9]+\.)([0-9]+)(<\/version>)/echo "\1\2$((\3+1))\4"/ge' pom.xml
          git add .
          git commit --amend --no-edit
          grep -E '<version>[0-9]+\.[0-9]+\.[0-9]+</version>' pom.xml
